"""Procedural guidance for transcript_edit without hard-coding a runtime script."""

from __future__ import annotations

from domains.prompting import PromptBlock

from ..branch import TRANSCRIPT_EDIT_DOMAIN_ID


TRANSCRIPT_EDIT_PROCEDURAL_GUIDANCE_SOURCE_REF = (
    "backend/domains/mapping/transcript_edit/prompting/surfaces/procedural_guidance.py"
)
TRANSCRIPT_EDIT_PROCEDURAL_GUIDANCE_VERSION = "v49"

TRANSCRIPT_EDIT_PROCEDURAL_GUIDANCE_TEXT = """\
Use this guidance to shape your movement through transcript-edit work. This is **guidance**, not a hard script. The harness still owns orchestration. You should apply judgment based on what the current run actually contains.

## The workflow chain
This domain is one machine with a dependency chain, not a pile of tools. Understand what each stage feeds, because the quality ceiling of every stage is set by the stage before it:

**t0 shape → atom inventory → point targets → crop packets → delegate observations → evidence-grounded determinations → honest closure → real geometry.**

- An atom is a **single value at a single spot on the page** — one number, one word, one mark that must be independently verified. The mapping-critical atoms are the raw parameters that will programmatically generate the final map: bearings, distances, directions, quantities, acreage, identifiers, monument names. If a parameter is wrong, the map is wrong; the prose between parameters is webbing — trust it by default, investigate it when it looks weird, but spend verification budget on the values that become geometry.
- A point crop can only land on a point. The whole crop apparatus — point targeting, template or explicit windows, the master overlay, adjustment — is built for single localized marks, not spans. The point identifies the exact atom or mark under investigation. The observation window may legitimately contain surrounding words, a line continuation, a neighboring symbol, or another visual anchor needed to interpret that atom. A contextual window does not turn the atom into a span-shaped resolution unit: the unit of accountability and the visual scope of observation do not have to be identical. To the degree an "atom" is actually a span, to that degree the point-crop machinery is being sabotaged: the window cannot contain the claim, the dot stops meaning anything, and the packet stops being evidence.
- A delegate can only verify what its supplied evidence packet shows. The delegate's entire world is the packet you curated; a precise atom gives the delegate one mark to read and report. A span-shaped atom forces the delegate to adjudicate text it cannot fully see — that is how delegate answers get muddy. Still ask delegates for all clearly visible text: the span is requested for opportunistic harvesting of nearby atoms, never as the determination target.
- A `determined_value` is only as trustworthy as the read that earned it, and closure is only as honest as its determined values. Deed-to-IR relies on the transcript and its recorded determinations to construct geometry. A wrong earned reading can propagate into the map; accurate text and honest uncertainty here directly affect downstream reliability.

Every stage inherits the previous stage's discipline or its corruption. Atomize precisely and the machine runs clean: points land, crops read, delegates report what the packet supports, and honest determinations make honest closure possible.

## Run sanity guide
Early run is inventory. Orient from T0 drafts, keep one useful T0 pinned, and build the work universe fast. Inventory is atom capture, not proof. Capture the details downstream mapping will consume as parameters: numbers, directions, measurements, quantities, location facts, boundary facts, identifiers, and other operative values. If a detail is likely not a parameter or handoff-critical fact, do not let it crowd the graph.

Atoms need candidate values so future turns know what exact page detail the unit refers to. A candidate is a placeholder, not earned truth. Use T0 wording as a reference handle, but do not give it truth weight.

Do not bundle atoms. If something is a number or small operative value, it probably needs its own covered unit. The degree an atom becomes a span is the degree inventory failed; bad atomization poisons point crops, delegates, and closure. Drop prose tails unless the tail is genuinely mission-critical; if it is vital, make the tail its own atom or atoms when feasible so downstream cropping still has a real target. Prose webbing between values is usually trusted unless it looks weird. Capture the values, organize groups sanely, and move on.

PLEASE do not chase determinations during inventory. That is a breach of run sanity. Uncertainty is fine at inventory stage: capture the work item, candidate shape, and unresolved question, then let resolution earn it later. Inventory is for listing the work universe, not spending turns proving it; violating this creates spin, wasted motion, and bad economics. Inventory `next_needed_step` should point to finishing inventory, not proving a value or source boundary. If the next step requires source-local evidence, that is resolution debt.

Resolution is verification. Determine whether the atoms are accurate and what their earned values are. Use the economic loop: point-crop the atom, send crop refs to delegates in coherent waves, integrate clear or honestly qualified reads, and repeat until the atom set is resolved as far as honest evidence allows. Point crops need bullseye placement because the point is the claim anchor; the window around it is a separate judgment about how much source context the observer needs.

Use a centered template when the atom and enough identifying context sit reasonably around the point. Use `window_extents_norm` when the visible context is materially asymmetric around that point — continuing mostly to one side, wrapping below, sitting near a source edge, or needing a neighboring word or symbol to stay identifiable. Templates remain the economical default for ordinary centered marks. Extents are not mandatory and not an advanced exception. `small_plus` / `small+` wide is one ordinary centered template, not a universal starting shape. Use a larger template, explicit extents, or a different method when the real unit or its visible context is not served by a tight centered crop. Do not knowingly start too tight merely because a later adjustment exists.

HITL is last resort. Ask the user when the source/evidence set cannot decide something after honest effort, or when external information is required.

Closure is short and earned. Once the atom set is resolved as far as possible and closure layers are honestly progressed, produce the required final artifacts/output, make the handoff posture explicit, and finish.

User steering is highest-signal. If the user gives direct information, treat it as first-class and do not override it with weaker source/delegate momentum. If it conflicts with evidence, surface the conflict and why, but the user's instruction controls the run.

## Transcript-edit work universe: t0 gives shape, source gives truth
Use t0 drafts aggressively for initial shape, not for earned truth. T0 is the fast substrate for visible document structure, local clusters, likely mission-critical atoms, omissions, contradictions, cutoffs, disagreement hotspots, and candidate readings. Use that broad shape as leverage; do not repeat the same broad-read method as if it were a new proof tier. A parent broad reread may orient or catch missing inventory, but for small exact map-critical atoms it usually does not beat the T0-shaped opening process.

The early job is not to investigate each atom's truth. The early job is to list the mission-critical atoms that exist. Walk the T0 shape top-to-bottom and build the visible work universe before resolution motion begins. Do not stop at disagreement points, broad buckets, first impressions, or the loudest conflict. **Do not crop or source-investigate just to prove inventory exists** — source-local proof belongs to resolution motion, not opening inventory. If T0 suggests a cutoff, continuation, contradiction, or missing source extent, register it as an open resolution item and move on. Inventory may name uncertainty; it must not chase it.

This does not mean T0 is true. Peer drafts are candidate readings, not authority. Their disagreements are useful clues, and their agreements can help you move faster, but neither agreement nor disagreement earns a value. Every T0 reading remains candidate/open until source-local evidence, delegated observation, HITL, or explicit blocker/no-further-progress posture resolves it. If later source review shows that T0 missed, merged, split, or misread a unit, amend the work universe then.

During inventory, preserve useful T0/source-shape scaffold in `stable_context` as explicit T0 memory, not earned document truth. This can be the full useful T0 shape or bounded local structure notes. Its job is durable shape memory: rough order, wrapping, local prose chain, and structural relation, so atom rows do not become isolated labels. Values still belong in atom `candidate_values` and must be earned later from source evidence. Keep stable_context bounded and high-signal; do not turn it into a junk drawer or second uncontrolled transcript. For local rows, use `attached_entity_ids` when it cheaply clarifies which atom ids belong to that source-shape segment, but do not spend turns grooming links; the context body is the main value.

Atomize actual atoms. This is a demand. Do it. Use T0 wording as the placeholder for atom registration; source proof earns or corrects it later. Atoms are granular exact details. A full call must NOT be a covered unit. NO EXCEPTIONS. If a call contains multiple unit-differentiated or independently checkable details, each detail is its own covered unit: one bearing/orientation detail, one distance/measurement detail, one quantity, one boundary/location detail, one named/identified reference, etc. The full call can only be a group or organizer. For the love of god, do not make the full call the atom; each exact item inside the call is the atom. DO NOT BREAK THIS. IF THIS IS VIOLATED IT CORRUPTS THE ENTIRE RUN: crops chase spans, delegates get muddy, closure lies, and downstream mapping inherits fake certainty.

When T0 shows an atom, do not leave the atom blank. Put the T0 representation in `candidate_values` as the placeholder for targeting and review. Candidate values are NOT earned truth; source proof later earns, corrects, or rejects them. This matters because the placeholder makes point-crop targeting more intuitive, gives the graph a tangible atom shape for the user to inspect, and gives future turns more context for reference and anchoring until an earned `determined_value` replaces it.

Broader source structures are useful as groups, but they are not atoms. A span is not an atom. Treat any covered-unit value or target phrase longer than about three words as span-shaped. The question is whether that span is genuinely allowed to remain a span unit. If it can be subdivided into granular details that can be targeted, verified, delegated, blocked, reopened, or closed independently, split it. Drop prose tails unless they are vital; if the tail matters, atomize the tail instead of stapling it onto the value. Critical mapping parameters and exact values need independent attention; do not bury them inside a long phrase just because the source text chains them together. Each granular mission-critical detail must be exposed as its own covered unit so it can be verified, delegated, blocked, reopened, or closed by itself. Before resolution, check the graph hard: if visible mission-critical atoms are missing, bundled, or span-shaped without a real reason, inventory is not done.

For this domain, a good opening inventory should usually be a **fast T0-shaped atomization pass**, not a long source-investigation phase. Before promoting from inventory into resolution, take one inventory-review turn. This is not source proof and it is not perfectionism; it is the strict sanity check that the map-critical atom universe is represented, the covered units are actual granular atoms, candidate placeholders exist where T0 shows the atom shape, and span-shaped units are rare and justified. Be extremely strict here: passing into resolution with bad atomization is expensive as hell because it creates crop spin, delegate mud, patch churn, and wasted motion almost automatically. If the answer is no, finish inventory. If the answer is yes, promote and move. Promote to `work_universe_posture: believed_adequate` and `motion_posture: resolution` once, from the current vantage point, you cannot name another visible map-critical atom that needs representation. Later discoveries can amend the graph, but obvious T0-visible atoms should not be deferred into expensive late backtracking. Inventory does not have to be perfect forever — it has to be honest enough that resolution can proceed without obvious missing units.

During resolution, apply the branch earned-reading standard before closing units. Keep early layer posture provisional with statuses like `unassessed`, `in_review`, or `open` until the relevant review coverage has actually been worked, and use `determination` when you want the provisional vs earned distinction to remain explicit in persisted state.

## Required persistent refs
Turn 1 inventory setup: put one useful T0 draft in `pin_refs` for every-turn hydration. The first continued point-crop resolution pocket must likewise put the current point-crop master overlay in `pin_refs`. Do not treat this as optional housekeeping. These are the two high-value control artifacts for the two phases: T0 keeps document-shape memory live while inventory is being built; the master overlay keeps the crop universe live while resolution is being earned.

`pin_refs` means durable attention support: the harness mechanically carries the ref forward and auto-surfaces/hydrates it before future choose-action turns until it is unpinned or expires. This matters because losing those control artifacts makes the run stupid and expensive. Without pinned T0, inventory drifts, misses visible atoms, and starts resolving from an incomplete work universe. Without pinned master overlay, point-placement memory disappears, the agent burns turns rehydrating or re-guessing, delegate outcomes become harder to compare against the targeted point universe, and crop spin gets worse.

If the run manually hydrates the T0 during inventory, or manually hydrates the master overlay during point-crop resolution, persistent-ref obedience failed. Correct `pin_refs` immediately instead of spending more hydrate turns.

## Operational reminders
- Keep `mission.closure_state` and `resolution_state.items` current as real work happens; do not wait for a final rationale to explain closure after the fact.
- If the strongest available in-run checks are exhausted on a material unresolved issue, emit HITL or explicit blocked posture rather than continuing indefinitely in posture-only turns.

## Transcript-edit run duration pressure
`run_context.iteration` is the current run turn count. In transcript-edit, treat it as an informational budget-pressure signal only. It is not an instruction, not a command to close, not a command to keep checking, and not a substitute for evidence judgment.

Current simple transcript-edit calibration:
- 0-10: `fresh_early_budget` — normal opening budget
- 11-20: `early_mid_budget` — normal working budget
- 21-30: `mid_budget` — mature working budget
- 31-40: `late_budget` — visibly long for this domain shape
- 41-50: `very_late_budget` — high budget pressure
- 51-60: `severe_budget` — severe budget pressure
- 61+: `critical_budget` — critical budget pressure

These labels exist so the run knows how long it has been working under transcript-edit expectations. They do not decide the next action. Use them only as awareness of elapsed budget pressure.

## Audit-sweep gap items
During the audit sweep before close or publish, if you discover that mission-essential visible content was never explicitly covered by any resolution item (for example, a visible sequence of thence-calls in a parcel was only implicitly assumed reviewed), the correct move is to **create a new explicit item for that coverage and work it**, not to annotate existing items to claim coverage they do not actually have. A late audit-gap item is a sign of healthy self-review, not a failure. Prefer adding the real work to the ledger over retrofitting closure language onto items that never touched that evidence.

## Source-reading packet workflow
Once resolution targets are known, use **source-reading packets** for exact atom truth. Broad source view and T0 give orientation and span shape; they usually do not earn small exact values. Do not turn atom verification into full-span proof. If the span itself is the unit, use a broader read; if the span matters because of internal details, isolate the pivotal atoms. The intended signal upgrade is deliberate localization: reduce visual scope, reduce candidate imprinting, put the decisive mark under focused attention, create reusable evidence refs, and give the user/auditor a targeted packet that directly demonstrates the claimed determination.

**`point_crops` is the ergonomic default** when target locations are known and localized image evidence is needed. This is about economics, not just convenience. It lets the agent mark the exact atom, choose the observation window that carries the context that atom needs, produce a master overlay for review, and create reusable crop refs for `hydrate_artifact_refs`, `delegate_subtask`, HITL, and audit. The point anchors the claim. The window decides how much surrounding source the observer receives. A contextual window does not enlarge the resolution atom. Do not knowingly create an obviously too-tight centered packet merely because the window can be resized later. Before the first packet, use the visible scaffold or master overlay to judge where the atom is, which surrounding anchor makes it identifiable, whether necessary context lies mostly left, right, above, or below, whether a source edge will constrain the window, and whether a centered template plausibly contains the useful evidence. When that context shape is already apparent, express it in the initial point-crop request. This is judgment, not a separate planning turn or a checklist. `window_extents_norm` stays inside the canonical point-crop mechanism: the point remains the anchor and the agent states how much source to include on each side. It is not the prohibited practice of abandoning points for unrelated generic crop boxes. Request grammar, mutual exclusions, edge clamping, and resolved-box fields live in the transform tool spec.

When creating point crops for known resolution atoms, fill `target_atom_id` with the exact atom id and use `target_hint` for the candidate value or short target reminder. These fields are not proof. They are deterministic wiring so the point key, worklist, timeline, and UI can show what each crop was intended to resolve.

Resolve by local clusters, not isolated drips. When inventory shows several atoms in the same visible region, place the largest coherent point packet that region can sensibly support. Each target may use the window shape appropriate to that atom — a centered template for an ordinary mark, explicit extents when that atom's context is uneven. Packet size is bounded by visual auditability and useful work, not by the largest possible batch and not by a fixed point count. The goal is one overlay review, one delegate wave, and one dense integration pass for a real subsection of work. Tiny repeated passes through the same source pocket are tedious and expensive unless the pocket truly only has tiny ready scope.

Stay in dense motion after the first wave. Do not start with a strong batch and then collapse into one-at-a-time tunnel vision unless the remaining work truly depends on one unresolved point. After handling the focused issue, ask what other low-friction work can be done in the same turn: integrate clear reads, send ready crop refs, place more obvious targets, repair a small patch failure, or advance another open atom. The economic win is sustained useful motion across the run, not one good batch followed by drip work.

Choose the window from what the overlay already shows. A centered template — including **`small_plus` / `small+` wide** — is the economical choice when the atom and sufficient identifying context are reasonably centered: enough local source to read the target, not a whole paragraph scan. Use `small` when the mark is isolated, `medium` or `large` when a centered local context is doing real work, and point-centered `width_norm` / `height_norm` when a template is close but the centered box needs different dimensions. Use `scale_x` / `scale_y` when that centered template is basically right but needs more or less room on one axis. Use `window_extents_norm` when the visible context is materially asymmetric around a correct point: a line continuing mainly to one side, a wrapped continuation below the mark, an atom near a source edge, a nearby word or symbol needed to distinguish the target, or a long horizontal label whose decisive mark is local but whose interpretation needs neighboring text. These are shapes of context, not source facts. Templates stay first-class. Extents are not always superior, and not every packet needs a custom window.

When the real unit is a short line-span or vital prose tail that cannot honestly be reduced to smaller atoms, use `span_line` instead of forcing a tight centered template. `span_line` is a width-heavy, line-height escape hatch for short text runs; it does not excuse lazy atomization.

Point-crop resolution is master-overlay-native. The master overlay is the control surface for the crop universe: coordinate lattice, target dots, letters, crop refs, and point table in one artifact. Put the master overlay ref in `pin_refs` for every-turn hydration during continued resolution pockets. This is not a nice-to-have. If the agent refuses to do it sensibly, the harness may eventually have to force-pin it mechanically; agent-authored pinning preserves agency only if the agent actually pins the high-value control artifact.

Use the master overlay for placement sanity and packet wiring. Do not hydrate `artifact_refs[]` after point-crop creation just to look around. That means every per-point crop image, not the master overlay, and it floods parent context, duplicates delegate work, and becomes a cost/spin vector. Normal point-crop memory is the pinned master overlay plus point key/review metadata. If the parent truly needs to inspect a crop image itself, hydrate that one specific crop ref by name. The parent curates packets, integrates graph state, and manages motion economy. Delegates do targeted local reads. Individual per-point **crop refs** are the packets for exact reads, `hydrate_artifact_refs`, `delegate_subtask`, and HITL context. The master overlay is for packet sanity; the crop refs are for reading.

On the promotion turn into point-crop resolution, hydrate and preferably pin the scaffold/master overlay so the coordinate lattice is visible before placing any point crops. Do not point-crop blind from the raw source image. The scaffold/master overlay is how bullseye coordinates become possible; point crops made before seeing the coordinate surface are guesses, and guesses create crop spin.

Aim point-crop targets bullseye-close to the target atom from the master-overlay/scaffold coordinate lattice. The point is the evidence anchor; the letter is only its handle. Put the point on the atom/mark itself, not near the phrase, not on the line generally, not where the crop might merely contain the atom. Do not place points from T0 sequence order, paragraph guesswork, or memory of the raw source image; use the coordinate grid and hit the visible mark. The more bullseye the better, but do not spin for perfect center if the atom is contained, readable, and anchored. If the unit is a span, the packet must fairly contain the span or the run should use a broader read and isolate any pivotal internal atoms separately. If the overlay shows the anchor is wrong, move the point. If the anchor is right and only the window is wrong — missing side context, too much irrelevant area, edge clipping, or insufficient vertical context — reshape the window and keep the point and target mapping. Do not move a correct anchor merely to drag a centered crop toward missing context. Prefer one meaningful reshaping, grounded in the overlay and existing packet metadata, over a sequence of small blind nudges. There is no fixed retry count and no one-adjustment ceiling; do not keep sampling materially unchanged evidence hoping for a different answer. Use **`point_crops_adjust`** by letter or alias. Use the point table as the coordinate record: adjust the existing letter or alias from its recorded coordinate instead of guessing the point again from scratch. When a subset matters and the full overlay is cluttered, **`point_crops_view`** can render a filtered overlay.

Use the atom evidence worklist before recreating packets. If an open atom already has a packet-ready-unused crop ref, send it forward, integrate from it, or deliberately retire it as bad before making another crop for the same atom or source pocket. A point packet is not done when created; its crop refs should feed determinations, unresolved observations, or an explicit abandonment. Reraking the same source patch while old packet refs sit unused is waste.

The branch already tells you that tool-returned image evidence is turn-local. If inspection reveals a legible detail, ambiguity, cutoff, contradiction, or verification result, record it in the item ledger, closure posture, and/or continuity journal during that same turn. Do not spend a separate turn re-hydrating a freshly returned master overlay when transform output already attached it as next-turn evidence — inspect the attached overlay, then act, adjust, delegate, escalate, or record insufficiency.

**Delegated exact reads:** once a source-reading packet is curated, critical or ambiguity-prone exact readings should normally go to a neutral `delegate_subtask` with `transcript_edit.visual_source_observation` unless there is a concrete reason not to. Delegation matters because it gives a more isolated focus to one micro mission, and also because independent delegate reads can run in parallel, increasing time efficiency of the run, which is extremely important to user experience. The parent owns curation and integration; the delegate receives only necessary refs and neutral task framing. Individual crop refs from the packet are natural `context_refs`. `point_crop_set_summary.delegation_lines` can help wire letter/alias → crop ref for delegate tasks. When a delegate is for a known atom or covered unit, set `target_entity_id` to that exact id and prefer the action alias to match it when clean; this is audit/UI wiring, not proof.

Before sending a delegate wave, sanity-check the master overlay and point key as the control surface. Point sanity: each point, labeled by its assigned letter, should appear in close visual proximity to the intended atom or mark, not somewhere obviously distant from it. Window sanity: the resolved bounds should plausibly contain the target plus the context needed for the requested observation. The parent is evaluating placement and coverage on the overlay, not rereading every crop image. `show:["box"]` is useful when the agent needs to inspect actual resolved window placement, especially for explicit extents, edge clipping, or a questioned packet. Box display is a review aid, not a requirement on every packet; the default pin/letter overlay remains appropriate when bounds do not need active review. The more bullseye the better, but close is fine and not worth spin. If a point is plainly far off, adjust the anchor before delegation. If the point is right and the window is not, reshape the window before delegation. Do not hydrate every crop to do this check; use the master overlay.

When a point packet has multiple ready crop refs, send what you can in a coherent delegate wave from those existing refs before rebuilding the same region. If ready refs remain after that wave, send them in the next wave when delegate/read motion is available. Do not lose ready packet refs and later recreate the same crops.

Delegate tasks should be narrow, atom-oriented, and non-leading, but not blind to what the isolated crop can actually provide. The point-crop packet is an attempted observation window, not proof that the requested atom is inside it. For visual-source delegates, ask for a structured target outcome (`target_presence`, `packet_assessment`, `target_anchor_text`, and `task_response`) plus all clearly visible non-partial text in `source_visible_text`. `target_presence` is packet-scoped: `absent` means not visible in this packet, never absent from the deed. Keep visible text line-separated; this is the net for opportunistic harvesting, so do not limit it to the target. Mark clipped edge text as partial/cut instead of completing it. If the target is absent or unclear, or the packet is `off_target`, `insufficient_context`, or `unreadable`, preserve that exact packet outcome instead of forcing nearby text into `task_response`. Identify the target in crop-local terms the delegate payload can support; avoid parent-only labels like first/second/third parcel or call order when that ordering is not visible in the crop. Supplied neighboring text or broader source refs may help interpret deed nomenclature and distinguish similar marks, but the requested value and peer candidates are never authority.

A delegate result is an observation, not a self-authenticating determination. `status: completed` says the observation call completed; it does not earn a value. Read the observation as a whole: `target_presence`, `packet_assessment`, `target_anchor_text`, `task_response`, and `source_visible_text` must tell a coherent story. When the delegate reports uncertainty, competing interpretations, clipping, or inadequate context, preserve that qualification; do not strip it to make the result look clean. Integrate the requested reading when the target is present and the packet and visible anchor actually support it — that is still only an observation. Earn the reading only when the source evidence supports it and material uncertainty has been resolved. If credible observations still conflict, preserve that conflict and keep the selected reading provisional. Later discriminating evidence may justify revising or earning the decision; record why the earlier alternative no longer holds. A completed call that fails that coherence test does not independently earn a reading.

As ordinary integration of the current work group, notice material inconsistencies already in hand: incompatible readings of the same identifiable mark, a response that does not answer the requested target, or a reading whose claimed anchor does not match the packet. This is not a separate sanity turn per atom, not a mandatory reread of every crop, and not a document-wide comparison sweep after every delegate wave. The master overlay remains the normal surface for assessing placement. Inspect a particular crop when a concrete unresolved question warrants it. The parent should reconcile packet-placement concerns against the master overlay rather than paying to reread every crop.

A material divergence from a candidate or an overlapping observation is not automatic acceptance or rejection; candidates remain non-authoritative, and delegate outputs do not become true by vote. When credible observations disagree about the same source detail, preserve the disagreement. PLEASE do not silently let the latest answer replace the earlier one. Neither recency, majority agreement, candidate familiarity, nor an observer's confidence establishes source truth. Matching observations to the same detail is your judgment; do not invent a mechanical comparison. Choose the best-supported current reading when useful work can proceed with it, and retain it as provisional while the material uncertainty remains. A further check is useful when it can distinguish the alternatives; repeating the same observation merely to obtain agreement is not progress. Do not require immediate adjudication of every discrepancy. If further investigation is unlikely to improve the answer economically, preserve the uncertainty and continue other work.

If a packet is `off_target` or `insufficient_context`, that is a packet outcome, not proof that the source lacks the target. Use that assessment together with the master overlay to see what materially needs changing. If the point is wrong, repair the anchor. If the point is right but context is clipped or asymmetric, reshape the window. If the packet is visually adequate and the mark remains ambiguous, more geometry adjustment may not improve the evidence. `unreadable` and genuine ambiguity are different from a bad window; no packet result mechanically selects the next action, and insufficient context does not mean always enlarge. If a materially improved packet still cannot answer the question, preserve uncertainty, move other work, or use honest HITL/blocker posture when appropriate. Adjust or retire the packet when justified, or preserve the unit as unresolved. When the target atom is genuinely clear, integrate it even if a larger phrase is clipped; do not let span-containment anxiety waste the atom read. Opportunistic harvesting means earn what the evidence actually gives you, even if the packet was created for a different target. If a delegate transcript or crop clearly reveals another open atom, use that same crop/delegate ref as evidence for that atom too; one read can close multiple details. Harvest only when the atom is cleanly visible, anchored, and cited to the shared crop/delegate ref. For span-like material, the ergonomic path is usually `span_line`, but if useful span content arrives through ordinary crops or delegates anyway, do not throw it away. Tile the earned surface across multiple crop/delegate refs when needed: if one packet clearly earns part of the span and another packet earns the remaining word or detail, cite both, earn the clean pieces, and leave only the genuinely missing piece open. Refine only when the atom itself is missing, ambiguous, off-target, or insufficiently anchored, and only when the refinement can change the evidence.

**Provisional transcript decisions (`apply_transcript_edits`):** when observers disagree or evidence is incomplete, you may write a best-current transcript reading as `determination: provisional` with appropriate existing `uncertainty_reasons`, credible `candidate_values` when they exist, an honest `verification_basis`, and the evidence refs that support or contest the selection — then continue work without pretending the value is earned. Applying a provisional reading does not make it earned. A correction to the text does not itself resolve the uncertainty. Keep the same `decision_id` when later evidence revises or earns that decision. Persist that decision into the working transcript through `apply_transcript_edits` when the reading is ready to integrate; do not leave the best-current text only in the graph. Keep corresponding investigation state honest under the existing graph contract; do not add another contested-value ledger or duplicate the complete decision provenance into graph prose. Where no defensible selection is available, preserve an honest unresolved reading or source limitation using the existing conventions. Continuing work is not permission to fabricate text. Do not repeatedly sample unchanged evidence merely to manufacture agreement. Do not force immediate HITL solely because a provisional value exists. The provisional decision record makes uncertain readings available for later review and deed-to-IR investigation. A mapping sanity issue may give a reason to revisit a reading; geometric convenience does not establish what the source says. Do not ignore a material issue because deed-to-IR will supposedly fix it. Whether uncertainty permits handoff remains your existing scoped closure judgment.

If a patch fails after a source-reading packet or delegate result, do not treat that as a reason to reread the source or rerun the same delegate. First repair the ledger entry from the rejected fragment or hydrate the prior `subtask:*` observation and integrate it. Reread only if the crop/delegate packet did not contain the target, the observation is ambiguous, or a better source packet is genuinely needed.

**Fair HITL packets:** the HITL question must match the packet. If the packet contains the decisive region, ask the human to read or adjudicate it. If the packet does not contain the target, refine or adjust the packet, or ask a source-limitation/scope question instead of a value question from the wrong view. Include relevant crop refs, filtered overlay refs, rendered locators, or annotated evidence in `hitl_request.context` (`evidence_refs`, `primary_evidence_ref`, `annotated_evidence_ref`, `question_regions`). When bounded choices are appropriate, include safe non-forcing options such as `Unable to determine` or `Other / needs nuance`.

Refinement should earn its keep. If adjusting the packet or re-reading the same refs does not make the reading clearer, record the limitation, ask HITL when a human can decide, or leave the unit open/blocked while you move the rest of the mission forward. When integrating short visual readings, assess the mark itself — not merely that evidence points to the right area. That assessment happens during ordinary integration of the current work group. Do not introduce a second read merely because a group is about to close; further inspection follows a concrete unresolved question.

## Batch motion and integration
Avoid one atom per setup/review/patch cycle when related work can be handled coherently, but do not force artificial batching. Clear readings can be patched in `state_patch` / `covered_units` while unclear ones remain open for refinement, HITL, or blocker posture. Graph patches record investigation state; they do not put text into the working transcript. That is `apply_transcript_edits`.

Do not force one micro-step per turn when the next actions are already clear and do not depend on each other. A good resolution turn may integrate returned reads, patch clear graph updates, place or adjust the next local point packet, use `hydrate_next` for one-shot next-turn evidence, keep required refs pinned, delegate ready crop refs, and leave residual misses for refinement. The run should feel like dense coordinated motion, not walking through mud one tiny action at a time.

## Save and handoff rhythm
If a working revision already exists, continue that lineage. Do not attempt to initialize it again.

Otherwise, initialize the working transcript from an exact in-scope T0 when that draft provides a useful source-shaped baseline. That is the normal economical way to create a transcript-bearing working revision; it avoids substantially re-authoring the same text when the baseline is useful. Lineage, hydration, and copyable text are necessary transport conditions; they do not by themselves establish that the candidate is useful as the working baseline. Dirty or uncertain T0 text may still be a useful baseline. Choosing the copy source is not ranking that peer as truth. It is not declaring the draft best, longest, consensus, or authoritative. It does not accept the copied text as verified, resolve graph items, earn readings, or treat peer agreement as evidence. Other T0 peers remain useful disagreement detectors. The copied text remains unverified candidate text until investigation and decision provenance support it.

You may decline a severely deficient, mismatched, or otherwise unhelpful baseline without first adjudicating every reading. Do not turn that judgment into a checklist or scoring system. Copy-source selection does not require exhaustive peer reconciliation. Evidence and peer disagreements are reconciled during ordinary investigation.

`save_workspace_artifact` remains available when you genuinely need to author the initial working artifact, even if a technically copyable T0 exists. Initialization is the normal economical path when it fits, not a mandatory phase or gate.

Do not wait until the draft looks finished, verified, or publishable. Known uncertainty or correctable transcription errors do not prevent initialization; they are why the working artifact exists. Initialization copies the exact T0 text into both transcript lanes, creates an empty decision ledger, and verifies nothing. Saving it does not verify those readings. Preserve source wording, uncertainties, and cutoffs honestly. Do not manufacture certainty to make the initial draft look finished.

`source_transcript_verbatim` remains the first output obligation; the domain branch owns the detailed lane contract, the artifact/authority distinction, and expected payload keys. The evolving working artifact may begin as unverified candidate text. The published output must still satisfy the domain's full source-observed transcript, provenance, uncertainty, and handoff obligations. Initialization must not weaken that final standard.

The working transcript is the product taking shape during the investigation. When a coherent group of readings is ready to integrate, apply those decisions to the current working revision with `apply_transcript_edits` while their evidence and uncertainty are still clear. Source-supported corrections and unchanged-text confirmations subsequently enter through `apply_transcript_edits`, using the returned exact working revision. Cadence is judgment: do not require one write per atom, a write every turn, or a fixed batch size. Request shape, identity-verification (`expected_text == replacement_text`), uncertainty fields, lane rules, and the nonbatchable contract live in the tool spec. Do not accumulate a second transcript in resolution summaries and leave the artifact to be reconstructed at the end. That loses decisions, makes final reconciliation expensive, and prevents the user and downstream agent from seeing what the run has actually established.

The branch owns the artifact/authority distinction: a graph update is not a persisted transcript edit. After a successful apply result, use the returned exact revision for subsequent edits. If an apply is refused, retain the investigation's valid findings and repair the request using the actual current revision — do not reread the source merely because a write failed. Keep graph updates concise; do not duplicate the complete decision ledger inside resolution summaries.

Near the end of the run, treat review as reconciliation rather than a fresh investigation. Publication performs the final reconciliation of the selected working revisions and their provenance. Compare the saved transcript and its decision provenance with material determinations, provisional readings, HITL decisions, remaining limitations, the closure ledger, resolution items, blockers, and evidence metadata. A provisional reading may support continued work and an honestly qualified handoff under existing closure policy; this is not a requirement that all decisions be earned before publication. Repair actual discrepancies. Do not reconstruct the entire transcript from accumulated turn history. If the artifact is handoffable for the available scope and only non-critical polish remains, publish/complete instead of stretching the run.

## What not to do
- Do not earn mapping-critical exact values from broad page or paragraph familiarity when a point-crop packet, localized crop ref, delegated read, or fair HITL packet can make the decisive mark directly inspectable.
- Do not hand-design one-off generic crop boxes as the normal path when point-crop targets and packets would express the target with less coordinate burden. `window_extents_norm` is still a point-anchored crop, not that prohibited generic box.
- Do not keep re-hydrating the same broad set of refs when a packet ref or targeted read is available.
- Do not hydrate or inspect image evidence and move on without recording what it showed about the claim under review.
- Do not let repeated packet refinement replace an honest open/blocker/HITL posture when the source will not answer further in-run.
- Do not turn final review into a broad second investigation once the artifact and handoff posture are already honest.
"""


def build_transcript_edit_procedural_guidance_blocks() -> tuple[PromptBlock, ...]:
    return (
        PromptBlock(
            block_id="transcript_edit_procedural_guidance",
            layer="domain_guidance",
            owner=TRANSCRIPT_EDIT_DOMAIN_ID,
            source_path=TRANSCRIPT_EDIT_PROCEDURAL_GUIDANCE_SOURCE_REF,
            version=TRANSCRIPT_EDIT_PROCEDURAL_GUIDANCE_VERSION,
            text=TRANSCRIPT_EDIT_PROCEDURAL_GUIDANCE_TEXT,
        ),
    )
