"""Public model surface for Agent Kernel v0."""

from .actions import (
    ActionExecutor,
    ActionExecutorDeps,
    ArtifactOpener,
    Bundler,
    Compiler,
    DeedHydrator,
    DraftIRProposer,
    EvidenceRetriever,
    Georeferencer,
    Judge,
    PatchProposer,
    StatusSummarizer,
    Validator,
)
from .kernel import KernelLoop, KernelLoopOutput, RunArtifactPersistence, run_kernel
from .session import KernelSessionManager, SessionPersistence
from .tooling import CorpusArtifactOpener, CorpusDeedHydrator, DraftIRFilesystemProposer
from .budgets import BudgetSnapshot, BudgetStatus, BudgetTracker
from .models import (
    ActionType,
    KernelClaimabilityStatus,
    KernelDashboard,
    KernelBudgets,
    KernelFailureClassification,
    KernelGapSummary,
    KernelGoal,
    KernelLatestRefs,
    KernelNoProgressRisk,
    KernelRefusal,
    KernelRequest,
    KernelResult,
    KernelSessionStartRequest,
    KernelSessionStartResult,
    KernelState,
    KernelStepRequest,
    KernelStepResult,
    StepExecutionState,
    StopReason,
    TerminalOutcomeKind,
    TerminalOutcome,
)
from .no_progress import (
    GapSignal,
    NoProgressDetector,
    NoProgressStatus,
    build_iteration_fingerprint,
    compute_artifact_digests,
    compute_gap_signature,
)
from .run_artifact import ArtifactRef, RunArtifact, StepRecord, ValidationInline
from .state_machine import KernelEvent, TransitionError, advance_state, can_transition

__all__ = [
    "ActionType",
    "ActionExecutor",
    "ActionExecutorDeps",
    "ArtifactOpener",
    "ArtifactRef",
    "BudgetSnapshot",
    "BudgetStatus",
    "BudgetTracker",
    "Bundler",
    "Compiler",
    "CorpusArtifactOpener",
    "CorpusDeedHydrator",
    "DeedHydrator",
    "DraftIRFilesystemProposer",
    "DraftIRProposer",
    "EvidenceRetriever",
    "Georeferencer",
    "Judge",
    "KernelLoop",
    "KernelLoopOutput",
    "KernelSessionManager",
    "KernelBudgets",
    "KernelClaimabilityStatus",
    "KernelDashboard",
    "KernelFailureClassification",
    "KernelGapSummary",
    "KernelGoal",
    "KernelLatestRefs",
    "KernelNoProgressRisk",
    "KernelRefusal",
    "KernelRequest",
    "KernelResult",
    "KernelSessionStartRequest",
    "KernelSessionStartResult",
    "KernelState",
    "KernelStepRequest",
    "KernelStepResult",
    "GapSignal",
    "NoProgressDetector",
    "NoProgressStatus",
    "PatchProposer",
    "RunArtifact",
    "RunArtifactPersistence",
    "StopReason",
    "StatusSummarizer",
    "StepRecord",
    "StepExecutionState",
    "TerminalOutcome",
    "TerminalOutcomeKind",
    "Validator",
    "ValidationInline",
    "run_kernel",
    "SessionPersistence",
    "KernelEvent",
    "TransitionError",
    "advance_state",
    "can_transition",
    "build_iteration_fingerprint",
    "compute_artifact_digests",
    "compute_gap_signature",
]
