"""Public model surface for Agent Kernel v0.

**Canonical (preferred for new code):** ``KernelSessionManager``, session models, tools, state machine.

**Compatibility (explicit; do not extend as primary architecture):** ``run_kernel`` (see ``kernel.py``),
re-exported for CLI and legacy callers — see ``COMPATIBILITY.md``.
"""

# --- Actions & tools (shared deps for session + compatibility loop) ---
from .actions import (
    ActionExecutor,
    ActionExecutorDeps,
    ArtifactOpener,
    Bundler,
    Compiler,
    DeedHydrator,
    DraftIRProposer,
    EvidenceRetriever,
    Georeferencer,
    Judge,
    PatchProposer,
    StatusSummarizer,
    Validator,
)
# --- Compatibility: autopilot / CLI JSON loop (not step-driven session API) ---
from .kernel import KernelLoop, KernelLoopOutput, RunArtifactPersistence, run_kernel
# --- Canonical: step-driven kernel session ---
from .session import KernelSessionManager, SessionPersistence
from .tooling import (
    CorpusArtifactOpener,
    CorpusDeedHydrator,
    DraftIRFilesystemProposer,
    FeatureGraphBundlerTool,
    FeatureGraphCompilerTool,
    FeatureGraphJudgeTool,
    RetrievalEvidenceTool,
)
from .budgets import BudgetSnapshot, BudgetStatus, BudgetTracker
from .models import (
    ActionType,
    KernelClaimabilityStatus,
    KernelDashboard,
    KernelBudgets,
    KernelFailureClassification,
    KernelGapSummary,
    KernelGoal,
    KernelLatestRefs,
    KernelNoProgressRisk,
    KernelRefusal,
    KernelRequest,
    KernelResult,
    KernelSessionStartRequest,
    KernelSessionStartResult,
    KernelState,
    KernelStepRequest,
    KernelStepResult,
    StepExecutionState,
    StopReason,
    TerminalOutcomeKind,
    TerminalOutcome,
)
from .no_progress import (
    GapSignal,
    NoProgressDetector,
    NoProgressStatus,
    build_iteration_fingerprint,
    compute_artifact_digests,
    compute_gap_signature,
)
from .run_artifact import ArtifactRef, RunArtifact, StepRecord, ValidationInline
from .state_machine import KernelEvent, TransitionError, advance_state, can_transition

__all__ = [
    "ActionType",
    "ActionExecutor",
    "ActionExecutorDeps",
    "ArtifactOpener",
    "ArtifactRef",
    "BudgetSnapshot",
    "BudgetStatus",
    "BudgetTracker",
    "Bundler",
    "Compiler",
    "CorpusArtifactOpener",
    "CorpusDeedHydrator",
    "DeedHydrator",
    "DraftIRFilesystemProposer",
    "FeatureGraphBundlerTool",
    "FeatureGraphCompilerTool",
    "FeatureGraphJudgeTool",
    "DraftIRProposer",
    "EvidenceRetriever",
    "Georeferencer",
    "Judge",
    "KernelLoop",
    "KernelLoopOutput",
    "KernelSessionManager",
    "KernelBudgets",
    "KernelClaimabilityStatus",
    "KernelDashboard",
    "KernelFailureClassification",
    "KernelGapSummary",
    "KernelGoal",
    "KernelLatestRefs",
    "KernelNoProgressRisk",
    "KernelRefusal",
    "KernelRequest",
    "KernelResult",
    "KernelSessionStartRequest",
    "KernelSessionStartResult",
    "KernelState",
    "KernelStepRequest",
    "KernelStepResult",
    "GapSignal",
    "NoProgressDetector",
    "NoProgressStatus",
    "PatchProposer",
    "RunArtifact",
    "RetrievalEvidenceTool",
    "RunArtifactPersistence",
    "StopReason",
    "StatusSummarizer",
    "StepRecord",
    "StepExecutionState",
    "TerminalOutcome",
    "TerminalOutcomeKind",
    "Validator",
    "ValidationInline",
    "run_kernel",
    "SessionPersistence",
    "KernelEvent",
    "TransitionError",
    "advance_state",
    "can_transition",
    "build_iteration_fingerprint",
    "compute_artifact_digests",
    "compute_gap_signature",
]
