"""Field-name constants for ``PromptObservabilitySummary`` payload parsing."""

from __future__ import annotations

ZERO_INT_FIELDS = (
    "prompt_event_count",
    "consecutive_no_dispatch_turns",
    "repeated_state_patch_reason_code_streak",
    "consecutive_same_active_item_turns",
    "new_resolution_items_since_last_complete_run_attempt",
    "repeated_complete_run_without_state_change_count",
    "same_ref_bundle_reread_no_gain_streak",
    "same_item_same_ref_bundle_stall_streak",
    "same_item_hydrate_churn_no_gain_streak",
    "artifact_refresh_trap_risk_count",
    "repair_ready_without_artifact_write_count",
    "hitl_evidence_readiness_debt_count",
    "post_hitl_spin_count",
    "post_write_artifact_consistency_check_count",
    "covered_unit_count",
    "covered_units_with_candidates_count",
    "closed_candidate_units_missing_determined_value_count",
    "closed_value_units_missing_evidence_count",
    "earned_units_missing_verification_basis_count",
    "earned_units_missing_locator_count",
    "shared_unlocated_evidence_for_earned_units_count",
    "long_determined_value_units_count",
    "earned_before_local_evidence_count",
    "posthoc_recheck_needed_count",
    "earned_exact_with_broad_image_locator_count",
    "blocked_without_hitl_answerability_count",
    "human_answerable_blocker_without_hitl_count",
    "not_answerable_missing_reason_count",
    "answered_hitl_unconsumed_count",
    "complete_with_unconsumed_hitl_count",
    "hitl_consumed_unknown_prompt_count",
    "user_message_pending_count",
    "user_message_consumed_count",
    "user_message_deferred_count",
    "user_message_consumed_unknown_count",
    "artifact_state_dirty_since_write_count",
    "success_condition_count",
    "success_conditions_with_earned_determination_count",
    "success_conditions_with_verification_basis_count",
    "resolution_item_count",
    "sequenced_item_count",
    "sequenced_items_missing_scope_count",
    "sequenced_items_missing_index_count",
    "duplicate_sequence_positions_count",
    "sequence_scope_order_gaps_count",
    "atomic_item_count",
    "group_item_count",
    "group_items_without_subclaims_count",
    "items_with_evidence_count",
    "items_with_verification_basis_count",
    "items_blocking_count",
    "items_requires_hitl_count",
    "items_no_further_progress_count",
    "closed_items_count",
    "closed_items_without_earned_determination_count",
    "closed_items_without_basis_count",
    "closed_items_without_completion_criteria_count",
    "critical_closed_items_without_evidence_count",
    "critical_closed_items_without_verification_basis_count",
    "blocking_items_without_relations_count",
    "closure_dimension_count",
    "closure_dimensions_with_earned_determination_count",
    "closed_dimensions_without_earned_determination_count",
    "closed_dimensions_without_basis_count",
    "closed_items_with_open_dependencies_count",
    "explicit_non_blocking_without_notes_count",
    "notebook_shaped_graph_rows_count",
    "artifact_claim_inventory_suspect_count",
    "multi_action_turn_count",
    "single_action_turn_count",
    "max_actions_in_turn",
)

OPTIONAL_INT_FIELDS = (
    "turns_since_last_tool_execution",
    "turns_since_latest_refs_change",
    "turns_since_last_state_patch_applied",
    "turns_since_resolution_item_count_change",
)

STR_FIELDS = (
    "last_prompt_event_id",
    "last_state_patch_outcome",
    "last_state_patch_reason_code",
    "work_universe_posture",
)
